### PR TITLE
Update aspia_common_fr.ts

### PR DESCRIPTION
**Pull request by PhilippKrs**
mise à jour de la traduction

### CODE REVIEW

**Comment by dchapyshev** [comment]
Do you translate in a text editor or Qt Linguist? Every time you update translations, you break the building of the project. Under no circumstances use a regular text editor to perform translation! The translation should only be done in Qt Linguist.

**Comment by PhilippKrs** [comment]
> Do you translate in a text editor or Qt Linguist? Every time you update translations, you break the building of the project. Under no circumstances use a regular text editor to perform translation! The translation should only be done in Qt Linguist.

Thanks for the information, and sorry for the text update. 
From now on, I'll only be working with Qt Linguist.
Do I need to redo the "aspia_common_fr.ts" files?

**Comment by dchapyshev** [comment]
> > Do you translate in a text editor or Qt Linguist? Every time you update translations, you break the building of the project. Under no circumstances use a regular text editor to perform translation! The translation should only be done in Qt Linguist.
> 
> Thanks for the information, and sorry for the text update. From now on, I'll only be working with Qt Linguist. Do I need to redo the "aspia_common_fr.ts" files?

There is no need to redo anything, I have already fixed the problem areas.

**Comment by PhilippKrs** [comment]
> > > Do you translate in a text editor or Qt Linguist? Every time you update translations, you break the building of the project. Under no circumstances use a regular text editor to perform translation! The translation should only be done in Qt Linguist.
> > 
> > 
> > Thanks for the information, and sorry for the text update. From now on, I'll only be working with Qt Linguist. Do I need to redo the "aspia_common_fr.ts" files?
> 
> There is no need to redo anything, I have already fixed the problem areas.

Ok thank's

**Pull request merged**
